% Generated by tools/rdf-to-eyepl.mjs.

query(rdf(X0, X1, X2, X3)).

rdf(iri("https://example.org/alice"), iri("https://example.org/parent"), iri("https://example.org/bob"), iri("https://example.org/family")).
rdf(iri("https://example.org/bob"), iri("https://example.org/parent"), iri("https://example.org/carol"), iri("https://example.org/family")).

% Rules
% Derive relationships inside the named graph that supplied the source data.
rdf(S, iri("https://example.org/ancestor"), O, G) :-
  rdf(S, iri("https://example.org/parent"), O, G).

rdf(S, iri("https://example.org/ancestor"), O, G) :-
  rdf(S, iri("https://example.org/parent"), M, G),
  rdf(M, iri("https://example.org/parent"), O, G).
