% Generated by tools/rdf-to-eyepl.mjs.

query(rdf(X0, X1, X2, X3)).

rdf(iri("https://example.org/alice"), iri("https://example.org/claims"), triple(iri("https://example.org/bob"), iri("https://example.org/knows"), iri("https://example.org/carol")), default_graph).

% Rules
% Project an RDF 1.2 triple term into an ordinary asserted relationship.
rdf(S, iri("https://example.org/knows"), O, G) :-
  rdf(
    _,
    iri("https://example.org/claims"),
    triple(S, iri("https://example.org/knows"), O),
    G
  ).
