% Generated by tools/rdf-to-eyepl.mjs.

query(rdf(X0, X1, X2, X3)).

rdf(iri("https://example.org/sensorGraph"), iri("https://example.org/reportedBy"), iri("https://example.org/station7"), default_graph).
rdf(iri("https://example.org/sensor1"), iri("https://example.org/temperature"), literal("21.5", datatype("http://www.w3.org/2001/XMLSchema#string")), iri("https://example.org/sensorGraph")).

% Rules
% Join graph metadata in the default graph with data from the named graph.
rdf(S, iri("https://example.org/reportedBy"), Station, default_graph) :-
  rdf(
    iri("https://example.org/sensorGraph"),
    iri("https://example.org/reportedBy"),
    Station,
    default_graph
  ),
  rdf(
    S,
    iri("https://example.org/temperature"),
    _,
    iri("https://example.org/sensorGraph")
  ).
