% Generated by tools/rdf-to-eyepl.mjs.

query(rdf(X0, X1, X2, X3)).

rdf(iri("https://example.org/welcome"), iri("https://example.org/label"), literal("مرحبا", lang("ar", rtl)), default_graph).
rdf(iri("https://example.org/welcome"), iri("https://example.org/label"), literal("Welcome", lang("en", ltr)), default_graph).

% Rules
% Preserve RDF 1.2 base-direction metadata while deriving display labels.
rdf(S, iri("https://example.org/displayLabel"), Label, G) :-
  rdf(S, iri("https://example.org/label"), Label, G).
